name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get Date
      id: get-date
      run: |
        echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        packages: 'platform-tools'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsqlite3-dev lld cmake libffi-dev libssl-dev autoconf automake libtool pkg-config zlib1g-dev ccache texinfo
        pip install --upgrade pip
        # Устанавливаем стабильную и предсказуемую версию buildozer
        pip install "Cython<3.0.0" git+https://github.com virtualenv setuptools wheel

    - name: Build with Buildozer
      run: |
        # Запускаем сборку напрямую, так как buildozer сам скачает совместимый NDK r25b/r26
        buildozer android debug
      env:
        BUILDOZER_WARN_ON_ROOT: 0

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MediaDownloader-APK-${{ env.date }}
        path: bin/*.apk
